[[buildpacks]]
url = "https://github.com/heroku/heroku-buildpack-google-chrome"

[[buildpacks]]
url = "https://github.com/heroku/heroku-buildpack-nodejs"

[build]
builder = "heroku/buildpacks:20"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build.args]
NODE_ENV = "production"

[start]
cmd = "node server.js"
watchPatterns = ["/app/**/*"]

[phases.setup]
cmds = ["apt-get update && apt-get install -y fonts-liberation libappindicator3-1 xdg-utils"]
